// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csxoazpnhatnvioopndo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzeG9henBuaGF0bnZpb29wbmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjA3ODMsImV4cCI6MjA2MDczNjc4M30.S7U82W-dE1a5zypPv1h1vHiHb7Gn5MlMWqUdu0PmkBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);